export enum ProductReviewActionType {
    ADDING_PRODUCT_REVIEW = 'catalog/ADDING_PRODUCT_REVIEW',
    ADD_PRODUCT_REVIEW_SUCCESS = 'catalog/ADD_PRODUCT_REVIEW_SUCCESS',
    ADD_PRODUCT_REVIEW_FAILED = 'catalog/ADD_PRODUCT_FAILED '
}